version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:860061945305:task-definition/audit-severity-task:1"
        LoadBalancerInfo:
          ContainerName: "audit-myserverity"
          ContainerPort: "9092"
        PlatformVersion: "LATEST"